<?php
$pg = 'lead';

return [

    // -------------------------------
    // Communication Templates
    // -------------------------------
    "communicationTemplate-lead" => [
        "lead_entry_new_sms"                => "New Lead Entry SMS",
        "lead_entry_new_whatsapp"           => "New Lead Entry Whatsapp",
        "lead_entry_new_email"              => "New Lead Entry Email",
        "lead_lead_followup-entry_new_sms"      => "Lead Followup Entry SMS",
        "lead_lead_followup-entry_new_whatsapp" => "Lead Followup Entry Whatsapp",
        "lead_lead_followup-entry_new_email"    => "Lead Followup Entry Email",
        "lead_assignment_new_sms"           => "Lead Assignment SMS",
        "lead_assignment_new_whatsapp"      => "Lead Assignment Whatsapp",
        "lead_assignment_new_email"         => "Lead Assignment Email",
        "lead_followupreminder_new_sms"     => "Lead Followup Reminder SMS",
        "lead_followupreminder_new_whatsapp"=> "Lead Followup Reminder Whatsapp",
        "lead_followupreminder_new_email"   => "Lead Followup Reminder Email"
    ],

    // -------------------------------
    // Column Name Mapping
    // -------------------------------
    "columnNameMapping-lead" => [
        'ptr'                           => 'SNo',
        'lead_id'                       => 'ID',
        'potential_client_name'         => 'Name',
        'potential_client_mobile_number'=> 'Mobile',
        'potential_client_email'        => 'Email',
        'potential_client_address'      => 'Address',
        'product'                       => 'Product',
        'generated_by'                  => 'Generated By',
        'contact_by'                    => 'Assigned To',
        'visit_planned'                 => 'Visit On',
        'lead_contact_by'               => 'Contact By',
        'contact_date'                  => 'Date',
        'next_date'                      => 'Next Dt',
        'contact_response'              => 'Response',
        'contact_remark'                => 'Remark',
        'district'                      => 'Dist',
        'visit_date'                    => 'Visit On',
        'expectation'                   => 'Exp',
        'uploaded_docs'                 => 'Docs',
        'status'                        => 'Status',
        'options'                       => 'Options'
    ],

    // -------------------------------
    // Menu
    // -------------------------------
    "menuItem-lead" => [
        "admin"  => [],
        "portal" => []
    ],

    // -------------------------------
    // Page Structure
    // -------------------------------
    "pgStructure-lead" => [
        "lead" => [
            'forms/form'  => ['entry', 'followup-entry', 'settings', 'report', 'upload', 'advancedinfo'],
            'lists/list'  => ['list'],
            'views/view'  => ['proposal', 'home', 'document', 'profile', 'detail', 'history']
        ]
    ],

    // -------------------------------
    // Mandatory Options
    // -------------------------------
    "mandatoryOptionsBeforeUsing-lead" => [
        'missing_option' => [
            'Lead Modes'        => 'lead_contact_mode-json',
            'Lead Expectation'  => 'lead_expectation-json',
            'Lead Progress'     => 'lead_progress_level-json'
        ]
    ],

    // -------------------------------
    // Module Tables
    // -------------------------------
    "moduleTable-lead" => [
        "cyp_term",
        "cyp_activity",
        "cyp_advancedinfo",
        "cyp_allotment",
        "cyp_cash",
        "cyp_option",
        "cyp_upload",
        "cyp_notification",
        "cyp_message",
        "cyp_leadgeneration"
    ],

    // -------------------------------
    // Default Columns
    // -------------------------------
    "defaultColumns-lead" => [
        'entry'            => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'list'             => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'detail'           => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'report'           => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'sample_export'    => ['sno','potential_client_name','potential_client_mobile_number','potential_client_email','contact_by','expectation','next_date','contact_response','state','district','potential_client_address'],
        'selected_columns' => ['potential_client_name','potential_client_mobile_number','potential_client_email','contact_by','expectation','next_date','contact_response','state','district','potential_client_address']
    ],

    // -------------------------------
    // Mandatory Fields
    // -------------------------------
    "mandatoryFields-lead_entry" => ['potential_client_name','potential_client_email','potential_client_mobile_number','next_date'],
    "mandatoryFields-lead_followup_entry" => ['thread_parent','contact_remark'],
    "mandatoryFields-lead_visitplanner_entry" => ['visit_by_id','next_visit_date'],

    // -------------------------------
    // Date Fields
    // -------------------------------
    "dateFields-lead_entry" => ['contact_date','next_date'],
    "dateFields-lead_followup_entry" => ['contact_followup_date'],
    "dateFields-lead_visitplanner_entry" => ['next_visit_date'],

    // -------------------------------
    // Additional Fields
    // -------------------------------
    "additionalFields-lead_entry" => ['assigned_to'],
    "additionalFields-lead_followup_entry" => [],
    "additionalFields-lead_visitplanner_entry" => [],

    // -------------------------------
    // Lead Status
    // -------------------------------
    "lead_status-json" => [
        "1"   => "PROGRESS",
        "12"  => "CLOSED",
        "19"  => "LOST",
        "2"   => "DELETED",
        "11"  => "NC"
    ],

    // -------------------------------
    // Lead Progress Level
    // -------------------------------
    "lead_progress_level-json" => [
        'UNDER DISCUSSION' => 'UNDER DISCUSSION',
        'PROPOSAL SENT'    => 'PROPOSAL SENT',
        'FINAL DISCUSSION' => 'FINAL DISCUSSION',
        'DATA ERROR'       => 'DATA ERROR'
    ],

    // -------------------------------
    // Lead Contact Status / Report Type
    // -------------------------------
    "lead_contact_status-json" => [
        "contact_made"       => "Contact Made",
        "followups_done"     => "Followups Done",
        "no_followups"       => "No Followup Done",
        "upcoming_followups" => "Upcoming Followups",
        "missed_followups"   => "Missed Followups"
    ],

    // -------------------------------
    // Lead Next Contact Date
    // -------------------------------
    "lead_contact_after-json" => [
        "1 days"   => "1 Day",
        "4 days"   => "4 Days",
        "7 days"   => "7 Days",
        "15 days"  => "15 Days",
        "30 days"  => "1 Month",
        "60 days"  => "2 Months",
        "90 days"  => "3 Months",
        "180 days" => "6 Months",
        "365 days" => "1 Year"
    ],

    // -------------------------------
    // Lead Bulk Operation
    // -------------------------------
    "lead_bulk_operation-list" => [
        "view:detail" => "View Lead Details",
        "send:email"  => "Send Email",
        "send:sms"    => "Send SMS",
        "op:remove"   => "Delete Lead",
        "op:restore"  => "Restore Lead"
    ],

    // -------------------------------
    // Search Columns
    // -------------------------------
    "search_column-json" => ["potential_client_name","potential_client_mobile_number"],

    // -------------------------------
    // Lead Document Types
    // -------------------------------
    "lead_document-json" => ['proposal' => 'Proposal'],

    // -------------------------------
    // Portal & Admin Permissions
    // -------------------------------
    "permissionAdmin-lead" => [
        'restricted' => [
            '2' => [['pg' => $pg, 'sub_pg' => 'settings']],
            '3' => [['pg' => $pg, 'sub_pg' => 'settings']]
        ],
        'allowed' => []
    ],

    "permissionPortal-lead" => [
        'restricted' => [],
        'allowed'    => [
            ['pg' => $pg, 'sub_pg' => 'home'],
            ['pg' => $pg, 'sub_pg' => 'entry'],
            ['pg' => $pg, 'sub_pg' => 'list'],
            ['pg' => $pg, 'sub_pg' => 'upload'],
            ['pg' => $pg, 'sub_pg' => 'document'],
            ['pg' => $pg, 'sub_pg' => 'detail'],
            ['pg' => $pg, 'sub_pg' => 'history'],
            ['pg' => $pg, 'sub_pg' => 'followup-entry'],
            ['pg' => $pg, 'sub_pg' => 'report'],
            ['pg' => $pg, 'sub_pg' => "{$pg}-report"]
        ]
    ],

    // -------------------------------
    // Lead Product List
    // -------------------------------
    "lead_product-json" => [],

    // -------------------------------
    // Lead Reference
    // -------------------------------
    "lead_reference-json" => ['Select'],

];
