<?php
$pg = 'lead';
$commonSettingsRoute = '/settings';

return [
	'menuItem-lead' => [
    'admin' => [
        'parent' => [
            $pg => '#',
        ],
        'child' => [
            $pg => [
                ['Add New'   => "/{$pg}/create"],
                ['View List' => "/{$pg}/list"],
                ['Report'    => "/{$pg}/report"],
                ['Settings'  => "/{$pg}/settings"],
                [
                    'Plugin' => [
                        ['View Calendar' => "/{$pg}/plugin/calendar"],
                    ]
                ],
            ],
        ],
    ],
],

'sidebar-menu' => [
    [
        'title' => ucfirst($pg),
        'href'  => "/{$pg}",
        'items' => [
            ['title' => 'Home',      'href' => "/module/{$pg}/home"],
            ['title' => 'Add New',   'href' => "/module/{$pg}/create"],
            ['title' => 'View List', 'href' => "/module/{$pg}/list"],
            ['title' => 'Report',    'href' => "/module/{$pg}/report"],
            ['title' => 'Settings',  'href' => "/module/{$pg}/settings"],
            [
                'title' => 'Plugin',
                'items' => [
                    ['title' => 'View Calendar', 'href' => "/module/{$pg}/plugin/calendar"],
                ]
            ],
        ],
    ],
],

	"lead-message_text" => [
                        "next_visit_date_scheduled|true"	=>	"Visit Scheduled Successfully",
                        "next_visit_date_scheduled|false"	=>	"Visit Scheduling Failed",
	],
	"communicationTemplate-lead" => [
                        "lead_entry_new_sms"				=>	"New Lead Entry SMS",
                        "lead_entry_new_whatsapp"			=>	"New Lead Entry Whatsapp",
                        "lead_entry_new_email"				=>	"New Lead Entry Email",
                        "lead_lead_followup-entry_new_sms"		=>	"Lead Followup Entry SMS",
                        "lead_lead_followup-entry_new_whatsapp"	=>	"Lead Followup Entry Whatsapp",
                        "lead_lead_followup-entry_new_email"	=>	"Lead Followup Entry Email",
                        //"lead_thanksgiving_new_sms"		=>	"Lead Thanksgiving to Client SMS",
                        //"lead_thanksgiving_new_whatsapp"	=>	"Lead Thanksgiving to Client Whatsapp",
                        //"lead_thanksgiving_new_email"		=>	"Lead Thanksgiving to Client Email",
                        "lead_assignment_new_sms"			=>	"Lead Assignment SMS",
                        "lead_assignment_new_whatsapp"		=>	"Lead Assignment Whatsapp",
                        "lead_assignment_new_email"			=>	"Lead Assingment Email",
                        "lead_followupreminder_new_sms"		=>	"Lead Followup Reminder SMS",
                        "lead_followupreminder_new_whatsapp"=>	"Lead Followup Reminder Whatsapp",
                        "lead_followupreminder_new_email"	=>	"Lead Followup Reminder Email"
	],
	"columnNameMapping-lead" => [
		                'ptr'								=>	'SNo',
                        'lead_id'							=>	'ID',
                        'potential_client_name'				=>	'Name',
                        'potential_client_mobile_number'	=>	'Mobile',
                        'potential_client_email'			=>	'Email',
                        'potential_client_address'			=>	'Address',
                        'product'							=>	'Product',
                        'generated_by'						=>	'Generated By',
                        'contact_by'						=>	'Assigned To',
                        'visit_planned'						=>	'Visit On',
                        'lead_contact_by'					=>	'Contact By',
                        'generated_by'						=>	'Generated By',
                        'contact_date'						=>	'Date',
                        'next_date'							=>	'Next Dt',
                        'contact_response'					=>	'Response',
                        'contact_remark'					=>	'Remark',
                        'district'							=>	'Dist',
                        'visit_date'						=>	'Visit On',
                        'expectation'						=>	'Exp',
                        'uploaded_docs'						=>	'Docs',
                        'status'							=>	'Status',
                        'options'							=>	'Options'
	],
	"mandatoryOptionsBeforeUsing-lead" => [
                        'missing_option'	=>	[
                            'Lead Modes'			=>	'lead_contact_mode-json',
                            'Lead Expectation'		=>	'lead_expectation-json',
                            'Lead Progress'			=>	'lead_progress_level-json'
                        ]
	],
	"moduleTable-lead" => [
                        "terms",
                        "cyp_activity",
                        "cyp_advancedinfo",
                        "cyp_allotment",
                        "cyp_cash",
                        "cyp_option",
                        "uploads",
                        "cyp_notification",
                        "cyp_message",
                        "cyp_leadgeneration"
	],
	"defaultColumns-lead" => [ 
		                'entry'				=>	['lead_id', 'date', 'potential_client_name', 'potential_client_mobile_number', 'expectation', 'next_date', 'contact_response','tags', 'status'],
                        'list'				=>	['lead_id', 'date', 'potential_client_name', 'potential_client_mobile_number', 'expectation', 'next_date', 'contact_response','tags', 'status'],
                        'detail'				=>	['lead_id', 'date', 'potential_client_name', 'potential_client_mobile_number', 'expectation', 'next_date', 'contact_response','tags', 'status'],
                        'report'				=>	['lead_id', 'date', 'potential_client_name', 'potential_client_mobile_number', 'expectation', 'next_date', 'contact_response','tags', 'status'],
                        'sample_export'		=>	['sno', 'potential_client_name', 'potential_client_mobile_number', 'potential_client_email', 'contact_by', 'expectation', 'next_date', 'contact_response', 'state', 'district', 'potential_client_address'],
                        'selected_columns'	=>	['potential_client_name', 'potential_client_mobile_number', 'potential_client_email', 'contact_by', 'expectation', 'next_date', 'contact_response', 'state', 'district', 'potential_client_address']
	],
	"cronList-lead" => ['lead-followupreminders' => 'Lead Upcoming Followups'],

	"mandatoryFields-lead_entry_update" => ['potential_client_name','potential_client_email','potential_client_mobile_number','next_date'],

	"dateFields-lead_entry_update" => ['contact_date','next_date'],

	"additionalFields-lead_entry_update" => ['assigned_to'],

	"mandatoryFields-lead_followup_entry_update" => ['thread_parent','contact_remark'],

	"dateFields-lead_followup_entry_update" => ['contact_followup_date'],

	"mandatoryFields-lead_visitplanner_entry_update" => ['visit_by_id','next_visit_date'],

	"dateFields-lead_visitplanner_entry_update" => ['next_visit_date'],

	"listFilters-lead_list" => [
                        "admin"	=>	[
                            "category_filter"	=>	"Category/category/lead_category-json",
                            "date_filter"		=>	"Date/date/contact_date-json",
                            'nextdate' 			=>	"Next Date/range-next_date/filter_date_range-json",
                            "lead_generated_by"	=>	"Generated By/generated_by/lead_by-json",
                            "lead_contact_by"	=>	"Contact By/contact_by/lead_contact_by-json",
                            "state_filter"		=>	"State/state/indian_state-json",
                            "lead_response"		=>	"Response/contact_response/lead_contact_response-json",
                            'nextdate' 	=> "Next Date/range-next_date/filter_date_range-json",
                            "status-filter"		=>	"Status/status/lead_status-json"
                        ],
                        "portal" => [
                            "state_filter"		=>	"State/state/indian_state-json",
                            'nextdate' 	=> "Next Date/range-next_date/filter_date_range-json",
                            "lead_response"		=>	"Response/contact_response/lead_contact_response-json",
                        ]
	],
	"listFilters-lead_followup-entry_update" => [
                        'admin' =>	array(
                            $pg			=>	[
                                'Edit'			=>	"{$pg}/followup-entry/update"
                            ]
                        )
	],
	"listFilters-lead_lead-report_new" => [
                        "admin"	=>	[
                            'report_type_filter'	=> "Report Type/report_type/lead_report_type-json",
                            'report_level_filter' 	=> "Progress/report_subtype/lead_progress_level-json",
                            'report_response_filter' => "Response/report_subtype/lead_contact_response-json"
                        ],
                        "portal" => [
                            'report_type_filter'	=> "Report Type/report_type/lead_report_type-json",
                            'report_level_filter' 	=> "Progress/report_subtype/lead_progress_level-json",
                            'report_response_filter' => "Response/report_subtype/lead_contact_response-json"
                        ]
	],
	"lead_document-json" => [
		                'proposal'					=> 'Proposal'
	],
	"permissionAdmin-lead" => [
                        'restricted'=>	[
                            '2'	=>	[['pg' => $pg, 'sub_pg'	=>	'settings']],
                            '3'	=>	[['pg' => $pg, 'sub_pg'	=>	'settings']]
                        ],
                        'allowed'	=>	[]
    ],
	"permissionRestrictedAdmin-module" => [
                        ['pg' => $pg, 'sub_pg'	=>	'settings']
	],
	"permissionPortal-lead" => [
                        'restricted'	=>	[],
                        'allowed'		=>	[
                            ['pg' => $pg, 'sub_pg'	=>	'home'],
                            ['pg' => $pg, 'sub_pg'	=>	'entry'],
                            ['pg' => $pg, 'sub_pg'	=>	'list'],
                            ['pg' => $pg, 'sub_pg'	=>	'upload'],
                            ['pg' => $pg, 'sub_pg'	=>	'document'],
                            ['pg' => $pg, 'sub_pg'	=>	'detail'],
                            ['pg' => $pg, 'sub_pg'	=>	'history'],
                            ['pg' => $pg, 'sub_pg'	=>	'followup-entry'],
                            ['pg' => $pg, 'sub_pg'	=>	'report'],
                            ['pg' => $pg, 'sub_pg'	=>	"{$pg}-report"], // logic is different in portal_page_access_barricade
                        ]
	],
	"permissionAllowedPortal-module" => [
                        ['pg' => $pg, 'sub_pg'	=>	'home'],
                        ['pg' => $pg, 'sub_pg'	=>	'entry'],
                        ['pg' => $pg, 'sub_pg'	=>	'list'],
                        ['pg' => $pg, 'sub_pg'	=>	'report'],
                        ['pg' => $pg, 'sub_pg'	=>	"{$pg}-report"], // logic is different in portal_page_access_barricade
	],
	"permissionAllowedFiltersPortal-lead" => [
                        "entry"	=>	[
                            [
                                "generated_by"		=>	'{$login_type}-{$login_id}',
                                "contact_by"		=>	'{$login_type}-{$login_id}'
                            ],
                        ],
                        "list"	=>	[
                            [
                                "generated_by"		=>	'{$login_type}-{$login_id}',
                                "contact_by"		=>	'{$login_type}-{$login_id}'
                            ],
                        ],
                        "report"	=>	[
                            [
                                "generated_by"		=>	'{$login_type}-{$login_id}',
                                "contact_by"		=>	'{$login_type}-{$login_id}'
                            ],
                        ]
	],
	"formPrefills-lead_entry_new" => [
                        "columns"	=>	[
                            'product'		=>	'default_product',
                            'contact_mode'	=>	'default_contact_mode',
                            'state'			=>	'default_indian_state'
                        ],
                        "groups"	=>	[
                            'current_date'	=>	['contact_date']
                        ]
	],
	"search_column-json" => ["potential_client_name","potential_client_mobile_number"],

	"lead_contact_after-json" => [
		                "1 days"	=>	"1 Day",
                        "4 days"	=>	"4 Days",
                        "7 days"	=>	"7 Days",
                        "15 days"	=>	"15 Days",
                        "30 days"	=>	"1 Month",
                        "60 days"	=>	"2 Months",
                        "90 days"	=>	"3 Months",
                        "180 days"	=>	"6 Months",
                        "365 days"	=>	"1 Year"
	],
	"lead_bulk_operation-list" => [
                        "view:detail"			=>	"View Lead Details",
                        "send:email"			=>	"Send Email",
                        "send:sms"				=>	"Send SMS",
                        "op:remove"				=>	"Delete Lead",
                        "op:restore"			=>	"Restore Lead"
	],
	"lead_report_type-json" => [
                        "contact_made"			=>	"Contact Made",
                        "followups_done"		=>	"Followups Done",
                        "no_followups"			=>	"No Followup Done",
                        "upcoming_followups"	=>	"Upcoming Followups",
                        "missed_followups"		=>	"Missed Followups"
	],
	"lead_progress_level-json" => [
		                'UNDER DISCUSSION'	=>	'UNDER DISCUSSION',
                        'PROPOSAL SENT'		=>	'PROPOSAL SENT',
                        'FINAL DISCUSSION'	=>	'FINAL DISCUSSION',
                        'DATA ERROR'		=>	'DATA ERROR'
	],
	"lead_status-json" => [
                        "1"		=>	"PROGRESS",
                        "12"	=>	"CLOSED",
                        "19"	=>	"LOST",
                        "2"		=>	"DELETED",
                        "11"	=>	"NC"
	],
	"advancedInfo_connectors-json" => ["canbe_assigned"	=>	true]

];
