<?php
$pg = 'lead';

return [

    /* =========================
     | Status & Crons
     ========================= */
    "lead.statuses" => [
        "1"  => "PROGRESS",
        "12" => "CLOSED",
        "19" => "LOST",
        "2"  => "DELETED",
        "11" => "NC"
    ],

    "lead.crons" => [
        'lead-followupreminders' => 'Lead Upcoming Followups'
    ],

    /* =========================
     | Filters (Admin / Portal)
     ========================= */
    "lead.list-filters" => [
        "admin" => [
            "category_filter" => "Category/category/lead_category-json",
            "date_filter"     => "Date/date/contact_date-json",
            "nextdate"        => "Next Date/range-next_date/filter_date_range-json",
            "lead_generated_by" => "Generated By/generated_by/lead_by-json",
            "lead_contact_by"   => "Contact By/contact_by/lead_contact_by-json",
            "state_filter"    => "State/state/indian_state-json",
            "lead_response"   => "Response/contact_response/lead_contact_response-json",
            "status-filter"   => "Status/status/lead_status-json"
        ],
        "portal" => [
            "state_filter"  => "State/state/indian_state-json",
            "nextdate"      => "Next Date/range-next_date/filter_date_range-json",
            "lead_response" => "Response/contact_response/lead_contact_response-json",
        ]
    ],

    /* =========================
     | Bulk Operations
     ========================= */
    "lead.bulk-operations" => [
        "view:detail" => "View Lead Details",
        "send:email"  => "Send Email",
        "send:sms"    => "Send SMS",
        "op:remove"   => "Delete Lead",
        "op:restore"  => "Restore Lead"
    ],

    /* =========================
     | Default Columns
     ========================= */
    "lead.default-columns" => [
        'entry'  => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'list'   => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'detail' => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'report' => ['lead_id','date','potential_client_name','potential_client_mobile_number','expectation','next_date','contact_response','tags','status'],
        'sample_export' => ['sno','potential_client_name','potential_client_mobile_number','potential_client_email','contact_by','expectation','next_date','contact_response','state','district','potential_client_address'],
        'selected_columns' => ['potential_client_name','potential_client_mobile_number','potential_client_email','contact_by','expectation','next_date','contact_response','state','district','potential_client_address']
    ],

    /* =========================
     | Permissions & Restrictions
     ========================= */
    "permissionAdmin-lead" => [
        'restricted' => [
            '2' => [['pg'=>$pg,'sub_pg'=>'settings']],
            '3' => [['pg'=>$pg,'sub_pg'=>'settings']]
        ],
        'allowed' => []
    ],

    "permissionPortal-lead" => [
        'restricted'=>[],
        'allowed'=>[
            ['pg'=>$pg,'sub_pg'=>'home'],
            ['pg'=>$pg,'sub_pg'=>'entry'],
            ['pg'=>$pg,'sub_pg'=>'list'],
            ['pg'=>$pg,'sub_pg'=>'detail'],
            ['pg'=>$pg,'sub_pg'=>'history'],
            ['pg'=>$pg,'sub_pg'=>'followup-entry'],
            ['pg'=>$pg,'sub_pg'=>'report'],
            ['pg'=>$pg,'sub_pg'=> "{$pg}-report"],
        ]
    ],

    /* =========================
     | Communication Templates
     ========================= */
    "communicationTemplate-lead" => [
        "lead_entry_new_sms" => "New Lead Entry SMS",
        "lead_entry_new_whatsapp" => "New Lead Entry Whatsapp",
        "lead_entry_new_email" => "New Lead Entry Email",
        "lead_assignment_new_sms" => "Lead Assignment SMS",
        "lead_assignment_new_whatsapp" => "Lead Assignment Whatsapp",
        "lead_assignment_new_email" => "Lead Assignment Email",
        "lead_followupreminder_new_sms" => "Lead Followup Reminder SMS",
        "lead_followupreminder_new_whatsapp" => "Lead Followup Reminder Whatsapp",
        "lead_followupreminder_new_email" => "Lead Followup Reminder Email",
    ],

    /* =========================
     | DB Tables
     ========================= */
    "moduleTable-lead" => [
        "terms",
        "cyp_activity",
        "cyp_advancedinfo",
        "cyp_allotment",
        "cyp_cash",
        "cyp_option",
        "uploads",
        "cyp_notification",
        "cyp_message",
        "cyp_leadgeneration"
    ],

    /* =========================
     | Validations & Helpers
     ========================= */
    "mandatoryFields-lead-entry-update" => [
        'potential_client_name',
        'potential_client_email',
        'potential_client_mobile_number',
        'next_date'
    ],

    "dateFields-lead-entry-update" => [
        'contact_date',
        'next_date'
    ],

    "search-column" => [
        "potential_client_name",
        "potential_client_mobile_number"
    ],

    "lead-contact-after" => [
        "1 days"=>"1 Day",
        "4 days"=>"4 Days",
        "7 days"=>"7 Days",
        "15 days"=>"15 Days",
        "30 days"=>"1 Month",
        "60 days"=>"2 Months",
        "90 days"=>"3 Months",
        "180 days"=>"6 Months",
        "365 days"=>"1 Year"
    ],

    "advancedInfo-connectors" => [
        "canbe_assigned" => true
    ],

];
