<?php
$pg = 'test';

return [

    'test.crons' => [
        'test-remindertoexaminees' => 'Test Reminder Notification'
    ],

    'test.list-filters' => [
        "admin" => [
            'session'          => 'Session/session/session-json',
            'recipient'        => 'Recipient/recipient/recipient_grouped_simplified-json',
            'status'           => 'Status/status/test_status-json',
            'test_date_filter' => 'Date/date/test_date-json',
        ],
        "portal" => [
            'session'          => 'Session/session/session-json',
            'recipient'        => 'Recipient/recipient/recipient_grouped_simplified-json',
            'status'           => 'Status/status/test_status-json',
            'test_date_filter' => 'Date/date/test_date-json',
        ]
    ],

    'test.bulk-operations' => [
        "view:detail"      => "View Detail",
        "document:results" => "View Results",
        "op:remove"        => "Delete",
        "op:restore"       => "Restore"
    ],

    'test.default-columns' => [
        'entry' => [
            'test_id','package_name','test_name','test_date',
            'start_time','end_time','total_time','question_count',
            'language_question_status','all_recipients','tags','status'
        ],
        'list' => [
            'test_id','package_name','test_name','test_date',
            'start_time','end_time','total_time','question_count',
            'language_question_status','all_recipients','tags','status'
        ],
        'detail' => [
            'test_id','package_name','test_name','test_date',
            'start_time','end_time','total_time','question_count',
            'language_question_status','all_recipients','tags','status'
        ],
        'report' => [
            'test_id','package_name','test_name','test_date',
            'start_time','end_time','total_time','question_count',
            'language_question_status','all_recipients','tags','status'
        ],
        'sample_export' => [
            'sno','test_name','test_date','start_time',
            'end_time','total_time','question_count','language_question_status'
        ],
        'selected_columns' => [
            'test_name','test_date','start_time',
            'end_time','total_time','question_count','language_question_status'
        ]
    ],

    'test.documents' => [
        'question-paper' => 'Question Paper'
    ],

    'test.list-columns' => [
        'id','test_name','test_package','test_set','session',
        'recipient','test_date','total_time','question_count','status'
    ],

    'test.report-columns' => [
        'id','test_package','test_set','test_name','test_language',
        'test_format','test_structure','test_marking_format',
        'question_source','question_count','test_date','total_time',
        'start_time','end_time','is_strict_timing','max_attempts_allowed',
        'test_interface','instructions','instructions_translated',
        'created_for','response'
    ],

    'test-message_text' => [
        "autogenerated_test_from_pool|true"  => "Questions Added from Pool",
        "autogenerated_test_from_pool|false" => "Failed to Add Questions from Pool"
    ],

    'communicationTemplate-test' => [
        "test_entry_new_sms"       => "New Test Entry SMS",
        "test_entry_new_whatsapp"  => "New Test Entry Whatsapp",
        "test_entry_new_email"     => "New Test Entry Email",
    ],

    'columnNameMapping-test' => [
        'ptr' => 'SNo',
        'test_id' => 'ID',
        'test_name' => 'Name',
        'test_date' => 'Date',
        'start_time' => 'Start',
        'end_time' => 'End',
        'total_time' => 'Dur (mts)',
        'question_count' => 'Total Qns',
        'language_question_status' => 'Questions'
    ],

    'mandatoryOptionsBeforeUsing-test' => [
        'missing_option' => [
            'Test Category/Subjects' => 'test_category-json',
            'Test Levels'            => 'test_level-json'
        ]
    ],

    'moduleTable-test' => [
        "cyp_term",
        "cyp_activity",
        "cyp_advancedinfo",
        "cyp_allotment",
        "cyp_cash",
        "cyp_option",
        "cyp_upload",
        "cyp_notification",
        "cyp_message",
        "cyp_test",
        "cyp_test_question_multiplechoice",
        "cyp_test_question_pool_multiplechoice",
        "cyp_test_result"
    ],

    'mandatoryFields-test-package-entry-update' => [
        'package_name','package_information'
    ],

    'mandatoryFields-test-entry-update' => [
        'test_name','question_count','total_time'
    ],

    'test-format' => [
        "multiple-choice" => "Multiple-Choice",
        "multiple-choice-from-pool" => "Multiple-Choice From Pool"
    ],

    'test-interface' => [
        "portal" => "Student Portal"
    ],

    'test-question-source' => [
        "create-set" => "No Source, Create Set",
        "autogenerate-set-from-pool" => "Generate From Questions Pool"
    ],

    'test-pool-limit' => ['25','50','75','100'],

    'test-offline-sheet-format' => [
        'offline-sheet-inline' => 'Inline Questions',
        'offline-sheet-2cols'  => '2cols Questions'
    ],

    'subscriptionEntity-test' => [
        'test/package-entry'
    ],

];
