<?php

namespace Modules\Shared\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TermDistrictSeeder extends Seeder
{
    public function run(): void
    {
        $districts = [

            'Andhra Pradesh' => [
                'Anantapur',
                'Chittoor',
                'East Godavari',
                'Guntur',
                'Kadapa',
                'Krishna',
                'Kurnool',
                'Nellore',
                'Prakasam',
                'Srikakulam',
                'Visakhapatnam',
                'Vizianagaram',
                'West Godavari',
            ],

            'Arunachal Pradesh' => [
                'Tawang',
                'West Kameng',
                'East Kameng',
                'Papum Pare',
                'Lower Subansiri',
                'Upper Subansiri',
                'West Siang',
                'East Siang',
                'Upper Siang',
                'Lower Dibang Valley',
                'Dibang Valley',
                'Anjaw',
                'Lohit',
                'Changlang',
                'Tirap',
                'Longding',
            ],

            'Assam' => [
                'Baksa',
                'Barpeta',
                'Bongaigaon',
                'Cachar',
                'Darrang',
                'Dhemaji',
                'Dhubri',
                'Dibrugarh',
                'Goalpara',
                'Golaghat',
                'Hailakandi',
                'Jorhat',
                'Kamrup',
                'Kamrup Metropolitan',
                'Karimganj',
                'Kokrajhar',
                'Lakhimpur',
                'Morigaon',
                'Nagaon',
                'Nalbari',
                'Sivasagar',
                'Sonitpur',
                'Tinsukia',
                'Udalguri',
            ],

            'Bihar' => [
                'Araria',
                'Arwal',
                'Aurangabad',
                'Banka',
                'Begusarai',
                'Bhagalpur',
                'Bhojpur',
                'Buxar',
                'Darbhanga',
                'Gaya',
                'Gopalganj',
                'Jamui',
                'Jehanabad',
                'Katihar',
                'Khagaria',
                'Kishanganj',
                'Lakhisarai',
                'Madhepura',
                'Madhubani',
                'Munger',
                'Muzaffarpur',
                'Nalanda',
                'Nawada',
                'Patna',
                'Purnia',
                'Rohtas',
                'Saharsa',
                'Samastipur',
                'Saran',
                'Sheikhpura',
                'Sitamarhi',
                'Siwan',
                'Supaul',
                'Vaishali',
                'West Champaran',
            ],

            'Delhi' => [
                'Central Delhi',
                'East Delhi',
                'New Delhi',
                'North Delhi',
                'North East Delhi',
                'North West Delhi',
                'Shahdara',
                'South Delhi',
                'South East Delhi',
                'South West Delhi',
                'West Delhi',
            ],

            'Gujarat' => [
                'Ahmedabad',
                'Amreli',
                'Anand',
                'Banaskantha',
                'Bharuch',
                'Bhavnagar',
                'Dahod',
                'Gandhinagar',
                'Jamnagar',
                'Junagadh',
                'Kheda',
                'Kutch',
                'Mehsana',
                'Morbi',
                'Narmada',
                'Navsari',
                'Panchmahal',
                'Patan',
                'Porbandar',
                'Rajkot',
                'Sabarkantha',
                'Surat',
                'Surendranagar',
                'Vadodara',
                'Valsad',
            ],

            'Maharashtra' => [
                'Ahmednagar',
                'Akola',
                'Amravati',
                'Aurangabad',
                'Beed',
                'Bhandara',
                'Buldhana',
                'Chandrapur',
                'Dhule',
                'Gadchiroli',
                'Gondia',
                'Hingoli',
                'Jalgaon',
                'Jalna',
                'Kolhapur',
                'Latur',
                'Mumbai City',
                'Mumbai Suburban',
                'Nagpur',
                'Nanded',
                'Nandurbar',
                'Nashik',
                'Osmanabad',
                'Palghar',
                'Parbhani',
                'Pune',
                'Raigad',
                'Ratnagiri',
                'Sangli',
                'Satara',
                'Sindhudurg',
                'Solapur',
                'Thane',
                'Wardha',
                'Washim',
                'Yavatmal',
            ],

            'Rajasthan' => [
                'Ajmer',
                'Alwar',
                'Banswara',
                'Baran',
                'Barmer',
                'Bharatpur',
                'Bhilwara',
                'Bikaner',
                'Bundi',
                'Chittorgarh',
                'Churu',
                'Jaipur',
                'Jaisalmer',
                'Jalore',
                'Jhalawar',
                'Jhunjhunu',
                'Jodhpur',
                'Kota',
                'Nagaur',
                'Pali',
                'Rajsamand',
                'Sikar',
                'Udaipur',
            ],

            'Uttar Pradesh' => [
                'Agra',
                'Aligarh',
                'Ayodhya',
                'Azamgarh',
                'Bareilly',
                'Basti',
                'Deoria',
                'Etawah',
                'Firozabad',
                'Ghaziabad',
                'Gonda',
                'Gorakhpur',
                'Jhansi',
                'Kanpur Nagar',
                'Lucknow',
                'Mathura',
                'Meerut',
                'Moradabad',
                'Prayagraj',
                'Rae Bareli',
                'Sitapur',
                'Sultanpur',
                'Varanasi',
            ],
        ];

        $data = [];
        $order = 1;

        foreach ($districts as $state => $items) {
            foreach ($items as $district) {
                $data[] = [
                    'tenant_id'  => 1,
                    'status'     => 1,
                    'name'       => "$district, $state",
                    'slug'       => Str::slug($district),
                    'group'      => 'indian-districts',
                    'module'     => 'shared',
                    'sort_order' => $order++,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        DB::table('terms')->upsert(
            $data,
            ['slug', 'tenant_id'],
            ['status', 'updated_at']
        );
    }
}
